name: Build Debug APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Generate Debug Keystore
        run: |
          cd android/app
          rm -f debug.keystore
          keytool -genkey -v -keystore debug.keystore -alias androiddebugkey -keyalg RSA -keysize 2048 -validity 10000 -storepass android -keypass android -dname "CN=Android Debug,O=Android,C=US"

      - name: Build Release APK
        env:
          DISABLE_SVG: 1
        shell: bash
        run: |
          cd android
          chmod +x ./gradlew
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='debug.keystore' -PMYAPP_UPLOAD_KEY_ALIAS='androiddebugkey' -PMYAPP_UPLOAD_STORE_PASSWORD='android' -PMYAPP_UPLOAD_KEY_PASSWORD='android'

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: lx-music-release-apk
          path: android/app/build/outputs/apk/release/*.apk
          retention-days: 7
